// Regenerates src/data/zones.js from the IANA database.
//   npm run gen:zones
//
// The output is a plain data file with no runtime dependency: each entry is
// "Zone/Name|CC". Country *names* are not embedded — the browser derives them
// from the code via Intl.DisplayNames.
import { writeFileSync } from 'node:fs'
import ct from 'countries-and-timezones'

const zones = Object.values(ct.getAllTimezones())
  .filter((z) => !z.name.startsWith('Etc/'))
  .filter((z) => z.name !== 'Factory')
  .map((z) => z.name + '|' + (z.countries[0] || ''))
  .sort()

// UTC is not a country zone but people search for it constantly.
zones.unshift('UTC|')

const file = `// GENERATED by scripts/generate-zones.mjs — do not edit by hand.
// Every IANA time zone, as "Zone/Name|ISO-2 country code".
export const ZONE_TABLE = ${JSON.stringify(zones.join(','))}
  .split(',')
  .map((row) => row.split('|'))
`

writeFileSync(new URL('../src/data/zones.js', import.meta.url), file)
console.log('wrote', zones.length, 'zones')
